---
name: 'CI Mentoria E2E'
'on':
  workflow_dispatch: null
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    env:
      API_BASE_URL: 'http://localhost:4000'
      PORT: 4000
    steps:
      - name: 'Checkout do Repositório'
        uses: 'actions/checkout@v4'
      - name: 'Instalando as dependências'
        run: 'npm install'
      - name: 'Iniciar servidor de mocks'
        run: 'npm run mock-server &'
      - name: 'Iniciar servidor de api'
        run: 'npm run server &'
      - name: 'Executar testes'
        run: 'npx cypress run'


